// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AudioFrame = __t.object("AudioFrame", {
  id: __t.u64(),
  sessionId: __t.string(),
  clientId: __t.string(),
  bufName: __t.string(),
  ts: __t.f64(),
  pitch: __t.f64(),
  mel: __t.array(__t.f32()),
  fft: __t.array(__t.f32()),
});
export type AudioFrame = __Infer<typeof AudioFrame>;

export const Session = __t.object("Session", {
  sessionId: __t.string(),
});
export type Session = __Infer<typeof Session>;

export const SessionMember = __t.object("SessionMember", {
  id: __t.u64(),
  sessionId: __t.string(),
  clientId: __t.string(),
});
export type SessionMember = __Infer<typeof SessionMember>;

