apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: violin-server
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "violin-server"
    nginx.ingress.kubernetes.io/upgrade: "websocket"
    nginx.ingress.kubernetes.io/connection-upgrade: "Upgrade"
spec:
  ingressClassName: nginx
  rules:
  - host: violin.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: violin-server
            port:
              number: 8000
